#pragma once
#define UNICODE_SELECTED_MODES UC_WIN, UNICODE_MODE_WINCOMPOSE
#ifndef CONFIG_USER_H
#define CONFIG_USER_H

// #include QMK_KEYBOARD_CONFIG_H


#define TAPPING_TERM 175
#define TAPPING_TOGGLE 2

#endif
