#pragma once
#define UNICODE_SELECTED_MODES UNICODE_MODE_LINUX, UNICODE_MODE_WINCOMPOSE
#ifndef CONFIG_USER_H
#define CONFIG_USER_H
#define LAYER_STATE_8BIT

// #include QMK_KEYBOARD_CONFIG_H

#undef LOCKING_SUPPORT_ENABLE
#undef LOCKING_RESYNC_ENABLE
#define NO_ACTION_ONESHOT
#define NO_MUSIC_MODE
#define UNICODE_KEY_LNX LCTL(LSFT(KC_U))
#define UNICODE_TYPE_DELAY 25

#define TAPPING_TERM 175
#define TAPPING_TOGGLE 2

#endif
